apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: cleanup-workflows
  name: cleanup-workflows
  namespace: argo
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: argo
          containers:
          - name: cleanup-workflows
            image: lachlanevenson/k8s-kubectl:v1.14.2
            args: ['delete', 'workflows', '--all', '-n', 'argo']
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 10m
                memory: 10Mi
          restartPolicy: OnFailure