apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: cleanup-s3-bucket
  name: cleanup-s3-bucket
  namespace: argo
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup-s3-bucket
            image: littlejo/aws-cli-docker
            command: ['aws']
            args: ['s3', 'rm', 's3://k8s-argo-artifacts-bucket.bouweceunen.com', '--recursive']
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 10m
                memory: 10Mi
          restartPolicy: OnFailure